[package]
name = "lutgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
exoquant = "0.2.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.7.0"
imageproc = "0.23"

# bin dependencies
clap = { version = "4.2.7", features = ["derive"], optional = true }

[features]
default = ["bin"]
bin = ["clap"]

[[bin]]
name = "lutgen"
path = "src/bin.rs"
required-features=["bin"]
