[package]
name = "lutgen"
version = "0.5.0"
documentation = "https://docs.rs/lutgen"
keywords = ["image-processing", "color", "hald-clut", "lookup-tables", "gaussian"]
description = "A blazingly fast interpolated LUT generator and applicator for arbitrary and popular color palettes."
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true

[workspace]
members = ["palettes"]

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Ossian Mapes <self@ossian.dev>"]
repository = "https://github.com/ozwaldorf/lutgen-rs"
categories = ["multimedia::images"]

[workspace.dependencies]
clap = { version = "4.2", features = ["derive"] }

[dependencies]
exoquant = "0.2.0"
image = "0.24"
rand = "0.8"
rand_distr = "0.4"
rayon = "1.7"
kiddo = "2.1.1"

# bin dependencies
clap = { workspace = true, optional = true }
spinners = { version = "4.1.0", optional = true }
dirs = { version = "5.0.1", optional = true }
lutgen-palettes = { version = "0.2", path = "palettes", optional = true }

[features]
default = ["bin"]
palettes = ["lutgen-palettes"]
bin = ["clap", "spinners", "dirs", "palettes"]

[[bin]]
name = "lutgen"
path = "src/bin.rs"
required-features=["bin"]

[profile.release]
opt-level = "z"

[profile.test]
inherits = "release"
